nodered:
  replicaCount: 1
  image: nodered/node-red
  tag: latest
  service:
    type: ClusterIP
    port: 1880
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: nodered.local
        paths: ["/"]
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

postgres:
  replicaCount: 1
  image: postgres
  tag: latest
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

grafana:
  replicaCount: 1
  image: grafana/grafana
  tag: latest
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: grafana.local
        paths: ["/"]
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

keycloak:
  replicaCount: 1
  image: jboss/keycloak
  tag: latest
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: keycloak.local
        paths: ["/"]
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  env:
    KEYCLOAK_USER: admin
    KEYCLOAK_PASSWORD: admin

minio:
  replicaCount: 1
  image: minio/minio
  tag: latest
  service:
    type: ClusterIP
    port: 9000
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  env:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123

mongodb:
  replicaCount: 1
  image: mongo
  tag: latest
  service:
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

mysql:
  replicaCount: 1
  image: mysql
  tag: latest
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  env:
    MYSQL_ROOT_PASSWORD: mysql

kafka:
  replicaCount: 1
  image: wurstmeister/kafka
  tag: latest
  service:
    type: ClusterIP
    port: 9092
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: kafka.local
        paths: ["/"]
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  env:
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

rabbitmq:
  replicaCount: 1
  image: rabbitmq
  tag: latest
  service:
    type: ClusterIP
    ports:
      - name: amqp
        port: 5672
      - name: management
        port: 15672
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: rabbitmq.local
        paths: ["/"]
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

prometheus:
  replicaCount: 1
  image: prom/prometheus
  tag: latest
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: prometheus.local
        paths: ["/"]
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
