apiVersion: v1
kind: Service
metadata:
  name: nodered
spec:
  type: {{ .Values.nodered.service.type }}
  ports:
    - port: {{ .Values.nodered.service.port }}
      targetPort: 1880
  selector:
    app: nodered
